# Generated by Django 4.0 on 2024-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time_period_unit',
        ),
        migrations.AlterField(
            model_name='item',
            name='time_period',
            field=models.CharField(choices=[('Час', 'Час'), ('Сутки', 'Сутки'), ('Месяц', 'Месяц')], max_length=20, verbose_name='Период времени'),
        ),
    ]
